### ISSUE TITLE
Local paths as dependencies

### ISSUE THREAD

**Issue by truedat101** [jodinathan/typings#18]
in ts2dart pubspec.yaml, this default set up is hard to catch when running the first time.  A rational default is to set this for the git repo and not the local path. 

```
dependency_overrides:
  code_builder:
   # git: https://github.com/jodinathan/code_builder
   path: /Users/jonathanrezende/Projects/dart/public/code_builder
```
